/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Syamsir-Sarul
 */
import javax.swing.JOptionPane;
import java.sql.*;
public class CardPanel extends javax.swing.JPanel {

    /**
     * Creates new form CardPanel
     */
    public CardPanel(int Id,String Judul,String MatPel, String tanggal, String Prioritas, String Deskripsi, boolean Complete, String UsernameAkun) {
        initComponents();
        this.tfId.setVisible(false);
        this.tfId.setText(String.valueOf(Id));
        this.tfJudul.setText(Judul);
        this.MataPelajaran.setText(MatPel);
        this.tfTanggal.setText(tanggal);
        this.Prioritas.setText(Prioritas);
        this.tfDeskripsi.setText(Deskripsi);
        this.cbCard.setSelected(Complete);
        this.tfUsernameAkun.setText(UsernameAkun);
        this.tfUsernameAkun.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfTanggal = new javax.swing.JLabel();
        Prioritas = new javax.swing.JLabel();
        cbCard = new javax.swing.JCheckBox();
        btnEdit = new javax.swing.JLabel();
        btnHapus = new javax.swing.JLabel();
        MataPelajaran = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfJudul = new javax.swing.JLabel();
        tfDeskripsi = new javax.swing.JLabel();
        tfUsernameAkun = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        tfTanggal.setBackground(new java.awt.Color(51, 255, 0));
        tfTanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTanggal.setText("Deadline");

        Prioritas.setBackground(new java.awt.Color(51, 255, 0));
        Prioritas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Prioritas.setText("Prioritas");

        cbCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCardActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(51, 255, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/edit_32px.png"))); // NOI18N
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(51, 255, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/trash_32px.png"))); // NOI18N
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        MataPelajaran.setBackground(new java.awt.Color(51, 255, 0));
        MataPelajaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MataPelajaran.setText("Mata Pelajaran");

        tfId.setEditable(false);
        tfId.setBackground(new java.awt.Color(255, 255, 255));
        tfId.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfId.setText("Id");
        tfId.setBorder(null);
        tfId.setEnabled(false);

        tfJudul.setBackground(new java.awt.Color(51, 255, 0));
        tfJudul.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tfJudul.setText("JUDUL");

        tfDeskripsi.setBackground(new java.awt.Color(51, 255, 0));
        tfDeskripsi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfDeskripsi.setText("Deskripsi Tugas Yang Ada");

        tfUsernameAkun.setEditable(false);
        tfUsernameAkun.setBackground(new java.awt.Color(255, 255, 255));
        tfUsernameAkun.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfUsernameAkun.setText("Id");
        tfUsernameAkun.setBorder(null);
        tfUsernameAkun.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDeskripsi)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfJudul)
                        .addGap(42, 42, 42)
                        .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUsernameAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Prioritas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MataPelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfJudul)
                            .addComponent(tfUsernameAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(tfDeskripsi, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbCard)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MataPelajaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Prioritas))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        FrameCardFormEdit FormEdit = new FrameCardFormEdit(this.tfJudul.getText(),this.MataPelajaran.getText(),this.tfTanggal.getText(),this.Prioritas.getText(),this.tfDeskripsi.getText(),Integer.parseInt(this.tfId.getText()), this.tfUsernameAkun.getText());
        FormEdit.setVisible(true);
        TutupForm.closeForm(AppListTugas.class);
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus Tugas?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            // Tindakan yang diambil jika pengguna menekan tombol "Yes"
            try{
                String query = "DELETE FROM tugasSekolah WHERE Id=?";
                PreparedStatement preparedStatement = Koneksi.getConnection().prepareStatement(query);
                preparedStatement.setInt(1, Integer.parseInt(tfId.getText()));
                preparedStatement.executeUpdate();
                JOptionPane.showMessageDialog(null,"Tugas Telah Dihapus!!!","BERHASIL",JOptionPane.INFORMATION_MESSAGE);
                TutupForm.closeForm(AppListTugas.class);
                AppListTugas Aplikasi = new AppListTugas();
                Aplikasi.setUsernameAkun(tfUsernameAkun.getText());
                Aplikasi.ShowData(tfUsernameAkun.getText());
                Aplikasi.setVisible(true);
            }catch(SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"Tidak Dapat Terhubung Ke Database","GAGAL",JOptionPane.ERROR_MESSAGE);
            }
        } else if (response == JOptionPane.NO_OPTION) {
            // Tindakan yang diambil jika pengguna menekan tombol "No"
        }
        
    }//GEN-LAST:event_btnHapusMouseClicked

    private void cbCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCardActionPerformed
        // TODO add your handling code here:
        if(cbCard.isSelected()){
            try{
                String query = "UPDATE tugasSekolah SET Complete=? WHERE Id=?";
                PreparedStatement preparedStatement = Koneksi.getConnection().prepareStatement(query);
                preparedStatement.setBoolean(1, true);
                preparedStatement.setInt(2,Integer.parseInt(this.tfId.getText()));
                preparedStatement.executeUpdate();
            }catch(SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"Tidak Dapat Terhubung Ke Database","GAGAL",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            try{
                String query = "UPDATE tugasSekolah SET Compelete=? WHERE Id=?";
                PreparedStatement preparedStatement = Koneksi.getConnection().prepareStatement(query);
                preparedStatement.setBoolean(1, false);
                preparedStatement.setInt(2,Integer.parseInt(this.tfId.getText()));
                preparedStatement.executeUpdate();
            }catch(SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"Tidak Dapat Terhubung Ke Database","GAGAL",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cbCardActionPerformed

    int xx,yy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MataPelajaran;
    private javax.swing.JLabel Prioritas;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JCheckBox cbCard;
    private javax.swing.JLabel tfDeskripsi;
    private javax.swing.JTextField tfId;
    private javax.swing.JLabel tfJudul;
    private javax.swing.JLabel tfTanggal;
    private javax.swing.JTextField tfUsernameAkun;
    // End of variables declaration//GEN-END:variables
}
